spring.application.name=deiconnect-backend

spring.datasource.url=jdbc:mysql://localhost:3306/deiconnect?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false

server.port=7000
server.error.include-message=always
server.error.include-binding-errors=always

app.jwt.secret=K9f3XzP7mQ2wL8cR5tY1uV6nB0aD4HsE
app.jwt.expiration-ms=86400000

app.privacy.default-min-group-size=5

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=none

eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

logging.level.org.springframework.security=INFO
logging.level.com.deiconnect=DEBUG

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
