<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.deiconnect</groupId>
    <artifactId>deiconnect-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>deiconnect-parent</name>
    <description>DEIConnect Parent Aggregator POM</description>
    <modules>
        <module>dei-connect</module>
        <module>eureka-server</module>
        <module>api-gateway</module>
        <module>survey-service</module>
        <module>erg-service</module>
    </modules>
</project>
